version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT:-5000}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGODB_PORT=${MONGODB_PORT:-27017}
      - MONGODB_URL=database
      - TG_TOKEN=${TG_TOKEN}
      - TG_CHAT_ID=${TG_CHAT_ID}
    volumes:
      - backend-storage:/opt/app/storage
    networks:
      - node-webapp-network
  database:
    restart: always
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_NAME}
    networks:
      - node-webapp-network
volumes:
  backend-storage:
  mongodb-data:
networks:
  node-webapp-network:
    driver: bridge
